baseURL = "https://www.wheelergenealogy.com/"
languageCode = "en-us"
title = "Wheeler Genealogy"
theme = "blowfish"

[params]
  mainSections = ["posts"]
  enableSearch = true
  disableTextInHeader = true

  [markup.goldmark.renderer]
  unsafe = true

  [permalinks]
  posts = "/:year/:month/:day/:slug/"
  defaultContentLanguage = "en"

[languages.en]
  languageCode = "en-us"
  title = "Wheeler Genealogy"

[languages.en.params]
  logo = "img/wheeler-crest.png"

[params.header]
  layout = "fixed-fill-blur"

[params.homepage]
  layout = "background"
  homepageImage = "img/home-hero.jpg"
  showRecent = true
  showRecentItems = 9
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = true
  disableHeroImageFilter = false

[menu]
  [[menu.main]]
    name = "Start Here"
    pageRef = "/start-here/"
    weight = 12
 
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menu.main]]
    name = "Browse"
    pageRef = "/browse/"
    weight = 11

  [[menu.main]]
    name = "Surnames"
    pageRef = "/surnames/"
    weight = 13

  [[menu.main]]
    name = "Places"
    pageRef = "/places/"
    weight = 14

  [[menu.main]]
    name = "Posts"
    pageRef = "/posts/"
    weight = 15

  [[menu.main]]
    name = "Series"
    pageRef = "/series/"
    weight = 16

  [[menu.main]]
    name = "Stories"
    pageRef = "/stories/"
    weight = 20

  [[menu.main]]
    name = "About"
    pageRef = "/about/"
    weight = 30

  [[menu.main]]
    name = "Contact"
    pageRef = "/contact/"
    weight = 40

  [[menu.main]]
     name = "Citations"
     pageRef = "/citations/"
     weight = 60

[outputs]
home = ["HTML", "RSS", "JSON"]
