baseURL = "https://www.wheelergenealogy.com/"
languageCode = "en-us"
title = "Wheeler Genealogy"
theme = "blowfish"

[params]
  mainSections = ["posts"]
  enableSearch = true

  [markup.goldmark.renderer]
  unsafe = true

  [permalinks]
  posts = "/:year/:month/:day/:slug/"

[params.header]
  layout = "fixed-fill-blur"

[params.homepage]
  layout = "background"
  homepageImage = "img/home-hero.jpg"
  showRecent = true
  showRecentItems = 9
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = true
  disableHeroImageFilter = false

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    pageRef = "/posts/"
    weight = 15


  [[menu.main]]
    name = "Stories"
    pageRef = "/stories/"
    weight = 20

  [[menu.main]]
    name = "About"
    pageRef = "/about/"
    weight = 30

  [[menu.main]]
    name = "Contact"
    pageRef = "/contact/"
    weight = 40

[outputs]
home = ["HTML", "RSS", "JSON"]
