baseURL = "https://www.wheelergenealogy.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Wheeler Genealogy"
theme = "blowfish"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[permalinks]
posts = "/:year/:month/:day/:slug/"

[params]
mainSections = ["posts"]
enableSearch = true
disableTextInHeader = true

[params.header]
layout = "fixed-fill-blur"

[params.homepage]
layout = "background"
homepageImage = "img/home-hero.jpg"
showRecent = true
showRecentItems = 9
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = true
layoutBackgroundBlur = true
disableHeroImageFilter = false

[languages.en]
languageCode = "en-us"
title = "Wheeler Genealogy"

[languages.en.params]
logo = "img/wheeler-crest.png"

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Browse"
pageRef = "/browse/"
weight = 20

[[menu.main]]
name = "Posts"
pageRef = "/posts/"
parent = "Browse"
weight = 21

[[menu.main]]
name = "Stories"
pageRef = "/stories/"
parent = "Browse"
weight = 22

[[menu.main]]
name = "Series"
pageRef = "/series/"
parent = "Browse"
weight = 23

[[menu.main]]
name = "Surnames"
pageRef = "/surnames/"
parent = "Browse"
weight = 24

[[menu.main]]
name = "Places"
pageRef = "/places/"
parent = "Browse"
weight = 25

[[menu.main]]
name = "Tags"
pageRef = "/tags/"
parent = "Browse"
weight = 26

[[menu.main]]
name = "Search"
pageRef = "/search/"
parent = "Browse"
weight = 27

[[menu.main]]
name = "Start Here"
pageRef = "/start-here/"
weight = 30

[[menu.main]]
name = "About"
pageRef = "/about/"
weight = 40

[[menu.main]]
name = "Contact"
pageRef = "/contact/"
weight = 50
