baseURL = "https://www.wheelergenealogy.com/"
languageCode = "en-us"
title = "Wheeler Genealogy"
theme = "blowfish"

[params]
  mainSections = ["posts"]

  [markup.goldmark.renderer]
  unsafe = true

  [permalinks]
  posts = "/:year/:month/:day/:slug/"

[params.homepage]
  showRecent = true
  showRecentItems = 6


[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    pageRef = "/posts/"
    weight = 15


  [[menu.main]]
    name = "Stories"
    pageRef = "/stories/"
    weight = 20

  [[menu.main]]
    name = "About"
    pageRef = "/about/"
    weight = 30

  [[menu.main]]
    name = "Contact"
    pageRef = "/contact/"
    weight = 40
